### ISSUE TITLE
Chronus 1.3.2

### ISSUE THREAD

**Issue by VictorCintra** [Felipe-UnB/Chronus#1]
1. Ao deletar as linhas 3,4 ou 5, os dados da tabela que mostram a razão 68 e 76 também são deletados e o programa ''trava''. Erro que não acontece ao apagar somente a primeira coluna do dado.
   ![erro](https://cloud.githubusercontent.com/assets/17956328/14662285/1495c602-068b-11e6-87b8-7642141bccf1.jpg)
2. O tempo de processamento para gerar uma nova tabela com as razões 68 e 76 é proporcional à quantidade de dados excluídos, caso seja selecionada a linha inteira. Porém, ao excluir somente a primeira coluna dos dados escolhidos, o tempo de processamento torna-se homogêneo (rápido) independente da quantidade de dados selecionados.
3. O Chronus não está salvando automaticamente os ciclos excluídos. Ex.: Ao excluir certos ciclos de um dado e avançar para o próximo dado, ao retornar, os ciclos excluídos reaparecem. 

Obs.: Para o teste foi utilizado o Excel 2016 e 2010.

**Comment by Felipe-UnB** [comment]
Victor, você pode testar se esse bug persiste nas versões mais recentes? Em algum momento, eu busquei resolver estas questões amas acabei esquecendo de botar um ponto final.

**Comment by VictorCintra** [comment]
Boa noite Felipe,

Felizmente não aparece esse bug nas versões recentes. 

Abs!
