### ISSUE TITLE
Instalação ''Chronus 1.4.3''

### ISSUE THREAD

**Issue by VictorCintra** [Felipe-UnB/Chronus#2]
Ao instalar o Chronus, o excel bloqueia seu funcionamento por questões de segurança. Para solucionar basta ir em Opções do Excel > Central de Confiabilidade > Configurações da Central de Confiabilidade > Locais Confiáveis > Adicionar novo local > Selecionar o arquivo do Chronus.

**Comment by Felipe-UnB** [comment]
Obrigado, Victor, vou adicionar a sua sugestão ao guia de instalação!
