### ISSUE TITLE
Problemas ao rodar amostra no Neptune na passagem de um dia para o outro (madrugada)

### ISSUE THREAD

**Issue by rsmarimon** [Felipe-UnB/Chronus#4]
Após efetuar todos os procedimentos no Chronos e clicar em Run, a seguinte mensagem de erro aparece: "After sample X there is not any blank analysis. Please check this missing analysis, its name might be different than the one you selected (BCO)". Esse erro impossibilita a continuidade do processo. Para resolvê-lo, é necessário que se identifique, no Samlist, quais amostras foram feitas em uma dia e quais foram feitas em outro. Por exemplo, às 23:59 do dia 18/04, o último procedimento foi um tiro no ZR16, sendo que após o ZR16, todas as furos foram feitos no dia 19. Identificado isso, deve-se corrigir as datas nos arquivos .dynamic, criados pelo Evaluation. Para tal, abre-se os mesmo com o Excel e modifica-se as datas encontradas nas linhas A4 e A8. Deve-se modificar apenas as datas antes das 24:00, ou seja, até o ZR16 no nosso exemplo. Os procedimentos feitos depois da virada do dia não necessitam de modificação. Feito essas alterações, os arquivos estão prontos para serem rodados pelo Chronos sem mais problemas.

**Comment by Felipe-UnB** [comment]
Esse é um problema originado no Evaluation, programa que exporta os arquivos brutos do Neptune para o formato dynamic.exp (que nada mais são do que arquivos txt cujas colunas são delimitadas por tabulação). O Evaluation não preserva as datas das análises nos arquivos exportados (veja a figura abaixo). Ele atribui o dia em que as análises estão sendo exportadas. Por isso, se uma análise ocorreu na transição de um dia para o outro, a data nos arquivos dará a impressão de uma parte das análises foi realizada no início do dia e outra no final do mesmo. A solução para isso é mudar a data em cada um dos arquivos para a data correta, ou dividi-los em pastas de acordo com o seu horário.

Evaluation, the program we use to export Neptune files to tab-delimited (those used by Chronus), does not keep the data of analysis in the exported files. Actually, it assigns the export date to them. For most of the samples, this is not an issue. However, for those samples analyzed overnight, it seems that part of the analyses occurred in the first moments of the day and the others at the end of the day (see the figure below). The solution is to correct the date in each file or to put the files in separated folders based on the time they were created.

![errohorario](https://cloud.githubusercontent.com/assets/8608912/25299516/67d800e8-26d6-11e7-9dcd-9fce2ce887bc.JPG)
