### ISSUE TITLE
Exclusão de ciclos

### ISSUE THREAD

**Issue by rsmarimon** [Felipe-UnB/Chronus#5]
No tab SlpStdBlkCorr apertei o botão da lupa (opean anlysis by ID) e depois o da ampulheta (standard deviation test), fui na opção test all. Depois, fui passando um por um e clicando na ampulheta até os dados ficarem dentro do standard deviation. Contudo, alguns grãos nunca atingiam o estágio em que a mensagem "All cycles passed the 2 standard deviation test" aparece, mesmo com vários ciclos excluidos. O que fazer nesses casos?

**Comment by Felipe-UnB** [comment]
Dear rsmarimon, please check the tutorials section at the end of the following page https://github.com/Felipe-UnB/Chronus/wiki/2-Software-operation.
