### ISSUE TITLE
apagar ciclo individual

### ISSUE THREAD

**Issue by JulianaRezendeDeOliveira** [Felipe-UnB/Chronus#6]
Olá Felipe, 

1- A filtragem de ciclos automática (por desvio padrão=2) eu consegui executar, fiz um testar tudo. Porém não me recordo como proceder para apagar um ciclo específico que o programa não tenha apontado. 

2- Filtragem dos ciclos e depois filtragem geral, existe mais algum procedimento? Posso enviar para você ver se está legal e sugerir melhoras?

Obrigada pela atenção de sempre.

**Comment by Felipe-UnB** [comment]
Dear Juliana, please check the new Tutorials section at the end of the following page https://github.com/Felipe-UnB/Chronus/wiki/2-Software-operation.

**Comment by JulianaRezendeDeOliveira** [comment]
Felipe, está ocorrendo um erro quando rodo o "test all" na filtragem dos ciclos. O programa faz a filtragem normalmente, porém aparece uma aba nova em relação a alguma amostra ex: "004-ZR1N (4)_Plot". Ao mesmo tempo abre um novo excel mostrando um arquivo dynamic ex: "067-ZR29B.dynamic". O que será?

**Comment by Felipe-UnB** [comment]
Juliana, faça o printscreen da tela  e coloque aqui, por favor, pra eu ver qual mensagem está aparecendo.
Quanto à segunda pergunta, o programa lhe pergunta o seguinte:
Deseja preservar os ciclos? Ou seja, deseja utilizar os ciclos que você selecionou ou gostaria que ele considerasse novamente todos os ciclos. Responda que sim.
Deseja usar os mesmo brancos? isso serve par aoc aso de você ter indicado brancos e padrões diferentes daqueles que o próprio programa selecionou para as suas amostras (planilha samList, colunas F a L). Se você tiver mudado algum branco, diga a ele para manter. Caso contrário, tanto faz dizer para ele manter ou não. 

Esclarecidas?
Envie o print da tela!

Abraço

**Comment by JulianaRezendeDeOliveira** [comment]
Atenciosamente,

Ma. Juliana Rezende de Oliveira
Geóloga - doutoranda (UnB)
contato (65)992076109


________________________________
De: Felipe Valença <notifications@github.com>
Enviado: terça-feira, 9 de maio de 2017 16:37
Para: Felipe-UnB/Chronus
Cc: Juliana; Author
Assunto: Re: [Felipe-UnB/Chronus] apagar ciclo individual (#6)


Juliana, faça o printscreen da tela ecoloque aqui, por favor, pra eu ver qual mensagem está aparecendo.
Quanto à segunda pergunta, o programa lhe pergunta o seguinte:
Deseja preservar os ciclos? Ou seja, deseja utilizar os ciclos que você selecionou ou gostaria que ele considerasse novamente todos os ciclos. Responda que sim.
Deseja usar os mesmo brancos? isso serve par aoc aso de você ter indicado brancos e padrões diferentes daqueles que o próprio programa selecionou para as suas amostras (planilha samList, colunas F a L). Se você tiver mudado algum branco, diga a ele para manter. Caso contrário, tanto faz dizer para ele manter ou não.

Esclarecidas?
Envie o print da tela!

Abraço
