### ISSUE TITLE
test all 

### ISSUE THREAD

**Issue by JulianaRezendeDeOliveira** [Felipe-UnB/Chronus#7]
Após limpar os ciclos, na hora que faço RUN para refazer a tabela, dou sim para as duas abas? A primeira p/ preservar os ciclos selecionados e a segunda em relação aos brancos.

**Comment by Felipe-UnB** [comment]
Please, check this. https://drive.google.com/file/d/0B84eLpq7CTSaUU5zR2J5Y2FsRlE/view?usp=sharing
