### ISSUE TITLE
comentário "Calculating a good discordia age (ver 1.0)"

### ISSUE THREAD

**Issue by JulianaRezendeDeOliveira** [Felipe-UnB/Chronus#8]
Olá Felipe, 
Muito bom esse tutorial, era exatamente o que faltava para o avanço do meu tratamento. 
Como sugestão peço que coloque no final a referência do Schoene (2013).

Muito obrigada!!

**Comment by JulianaRezendeDeOliveira** [comment]
Felipe, pra mim não ficou muito claro como utilizar a ferramenta "LineFit". Não consigo achá-la no Chronus.

**Comment by Felipe-UnB** [comment]
Dear Juliana, please check the tutorial latest version. I added more information about the LifeFitYiPred function and also the references section (thanks for the tips).

I hope this helps,
Felipe

**Comment by Felipe-UnB** [comment]
Juliana, was the tutorial helpful?
