### ISSUE TITLE
Erro para funcionamento em 64bits

### ISSUE THREAD

**Issue by debemgeo** [Felipe-UnB/Chronus#9]
Segue em anexo a mensagem exibida sobre o erro. 
![msg chronus](https://user-images.githubusercontent.com/29739210/27607086-1454b42c-5b59-11e7-8b6a-26e2e6842874.PNG)

Trocar Long por LongPtr e adicionar PtrSafe.

**Comment by Felipe-UnB** [comment]
Next release will cover this topic. Thanks for your comment!

**Comment by Felipe-UnB** [comment]
https://github.com/Felipe-UnB/Chronus/releases/tag/v2.0.0_alpha.2
